name: Import GitHub Issues

on:
  workflow_dispatch:

jobs:
  import:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create issues from CSV
        uses: peter-evans/create-issue-from-file@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: MonDave101/project-dxts  # Replace this with your actual repo path
          data-file: .github/workflows/DXTS_Issues_List.csv # <- Updated path
          format: csv
          title-column: Title
          body-column: Body
          milestone-column: Milestone
